language: java
jdk:
 - openjdk11
#mono: none
sudo: required #or false
os: linux
dist: xenial # distribution linux ubuntu
branches:
  only:
    - main
    #- develop
    #except:
    #- uat
    #- feature
#before_script:
#env: #required upload files coverage
#  global:
#    - CODECOV_TOKEN=:a63810c9-ed26-4f57-908b-5cd35f128622
cache:
  directories:
    - $HOME/.m2
before_script:
  - chmod -R a+x devops
before_install:
  - chmod +x mvnw
script:
  - ./devops/compile.sh
  - ./devops/test.sh
  - ./devops/report.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./devops/build.sh
notifications:
  email:
    on_success: always
    on_failure: always