language: java
jdk:
- openjdk11
sudo: required
os: linux
dist: xenial
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2"
before_script:
- chmod -R a+x devops
before_install:
- chmod +x mvnw
script:
- "./devops/compile.sh"
- "./devops/test.sh"
- "./devops/report.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
- "./devops/build.sh"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: ms-firstdevopsjob-java-7c551a585d7d.json.enc
  project: ms-firstdevopsjob-java
  version: service-demo
  default: true
  on:
    all_branches: true
notifications:
  email:
    on_success: always
    on_failure: always
