language: java
jdk:
 - openjdk11
sudo: required #or false
os: linux
dist: xenial
branches:
  only:
    - main
#    - develop
script:
  - mvn clean package
  - mvn test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: ms-firstdevopsjob-java-7c551a585d7d.json #Name file keypair generated in gcp
    project: ms-firstdevopsjob-java #name project ID into GCP created
    version: service-demo
    default: true
    on:
      all_branches: true
# [END travis_deploy]