---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deployment-devops
  namespace: prod
  labels:
    app: service-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-devops
  template:
    metadata:
      labels:
        app: service-devops
    spec:
      containers:
      - image: denisdevsoa/simple-devops:latest
        name: service-devops
        ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-devops
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: service-devops
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
